---
name: Prune

on:
  schedule:
    - cron: "0 5 * * 3"
  workflow_dispatch: {}

jobs:
  ghcr:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Prune smoke test images
        uses: snok/container-retention-policy@v3
        with:
          image-names: fake-seam-connect
          image-tags: smoke-*
          cut-off: 1w
          keep-n-most-recent: 1
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GH_TOKEN }}
